name: Build and Push to ECR

on:
  push:
    branches:
      - main  # Adjust if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read   # Required to checkout code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::767397903302:role/github-actions-oidc-role
          role-session-name: github-actions
          aws-region: ap-south-2  # Change to your AWS region

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-2 | docker login --username AWS --password-stdin 767397903302.dkr.ecr.ap-south-2.amazonaws.com

      - name: Build Docker Image
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
          IMAGE_NAME="github-test"
          IMAGE_TAG="latest"
          ECR_REPO="$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_NAME"

          # Build Docker image
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

          # Tag the image for ECR
          docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG

          # Push to ECR
          docker push $ECR_REPO:$IMAGE_TAG
